# Generated by Django 2.1.7 on 2020-01-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summay',
            field=models.TextField(blank=True),
        ),
    ]
